### ISSUE TITLE
Escape double quotes in the normalization string in collation processing instead of when building website

### ISSUE THREAD

**Issue by Yuying-Jin** [FrankensteinVariorum/collationWorkspace#48]
@ebeshero  I would like to escape double quotes in the string normalized in collate.py. So far we tried to escape double quotes in typescript with regex when building the website; however, converting all the normalization strings to the valid JSON structure is too tricky. There are many complicated conditions to consider, and regex cannot meet the demand of all conditions. Escaping these double quotes in processToken() like below would be a good idea. 
```python
def processToken(inputText):
    return {"t": inputText + ' ', "n": normalize(re.sub(r'(“|”)', '\\\\\\1' ,inputText))}
```

This is the output sample with unit testing:
```python
{'n': '\\"hello world!\\"', 't': '“Hello world!” '}
```

**Comment by ebeshero** [comment]
@Yuying-Jin It looks like this would simply change the normalized strings so you can process them efficiently! (I wonder if it changes anything in the actual collation...) 

I can try it later tonight and run all the pipelines... Shouldn't we be worried about breaking things in the collation, though?

**Comment by Yuying-Jin** [comment]
@ebeshero Your concern is reasonable. I will test this function with some passages which includes double quotes.

**Comment by ebeshero** [comment]
Updating this from our discussion last week: We now want to replace the double quotes like this:

```
{'n': '<q>hello world!<q>', 't': '“Hello world!” '}
```

We can't make a close-tag for `<q>` because we have no reliable way of distinguishing the varieties of open-quote from close-quote in our source files.

**Comment by ebeshero** [comment]
Resolved with outputting `%q%` markers in the normalized tokens.
