### ISSUE TITLE
Resolve a Windows Character Encoding Issue

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/collationWorkspace#6]
@arrowarchive @nhammer514 @Yuying-Jin @ebeshero We discovered a problem for Windows in processing some of our collation when the files have unusual special characters. It's to do with Windows not normally handling Unicode UTF-8 characters. (We broke the collation on C11 to see this on multiple Windows computers today.) We also learned how to fix it, so we'll need **everyone** on a Windows computer to make sure they have this set up:

It's just a Windows Control Panel setting and it should not cause problems. (Changing this setting is necessary for our Frankenstein work, but it also will make unicode characters and text in multiple languages/alphabets easier to process). Here's how to change the settting with a useful visual: Look at the first answer with the screen captures:
https://superuser.com/questions/1033088/is-it-possible-to-set-locale-of-a-windows-application-to-utf-8 

Please see if you can do this (or we can do this during our next meeting this week.) 

Copying @raffazizzi too!

**Comment by arrowarchive** [comment]
@ebeshero Is this an issue exclusive to windows 10 or 11, or are all windows operating systems affected by this?

**Comment by ebeshero** [comment]
It will be a problem for any Windows system processing text files. But the convenient repair in the Control Panel is only available Windows 10 and later!
